spring.application.name=job-automation
server.port=9999
spring.main.web-application-type=none
TO_EMAIL=14krishanuadak26@gmail.com
FROM_EMAIL=krishanuadak19@gmail.com
NAUKRI_USERNAME=krishanuadak19@gmail.com
NAUKRI_PASSWORD=Krishanu@2000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krishanuadak19@gmail.com
spring.mail.password=zbue hvfb phbf fjcx

